# 一、ndarray
## 1.ndarray
### 多维性

In [9]:
#Jupyter 笔记本环境 安装numpy
!pip install numpy

Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 10.7 MB/s  0:00:00 eta 0:00:01


In [10]:
import numpy as  np

In [14]:
arr = np.array(5)
print(arr)
print(arr.ndim)   # arr的维度  0维   ndim ：dimensions （标量） 数组的维度

5
0


In [15]:
arr = np.array(   [1,2,3]  )
print(arr)
print('arr的维度:',arr.ndim)      # arr的维度  1维 向量

[1 2 3]
arr的维度: 1


In [17]:
arr = np.array(  [ [1,2,3] , [4,5,6]  ]  )
print(arr)
print('arr的维度:',arr.ndim)      # arr的维度  2维 矩阵

[[1 2 3]
 [4 5 6]]
arr的维度: 2


In [68]:
arr = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])
print(arr)
print('arr的维度:',arr.ndim)      # arr的维度  3维 矩阵

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
arr的维度: 3


# 同质性
## 数组有不同的数据 会自动进行 强制转换 （相同数据类型）

In [18]:
arr = np.array(  [ 1,'hello' ]  )
print(arr)
print('arr的维度:',arr.ndim)      # 同质性   数字和字符串 肯定会被转换为字符串。升维保留：更多信息被保留

['1' 'hello']
arr的维度: 1


In [19]:
arr = np.array(  [ 1,2.5 ]  )
print(arr)
print('arr的维度:',arr.ndim)

[1.  2.5]
arr的维度: 1


# 二、ndarray 属性

In [30]:
arr = np.array(1)
print(arr)
print('数组的形状：',arr.shape)
print('数组的wd：',arr.ndim)
print('元素的数据类型:',arr.dtype)

1
数组的形状： ()
数组的wd： 0
元素的数据类型: int64


In [32]:
arr = np.array([1,2,3])
print(arr)
print('数组的形状：',arr.shape)
print('数组的wd：',arr.ndim)
print('元素的数据类型:',arr.dtype)
print('元素的转置',arr.T)

[1 2 3]
数组的形状： (3,)
数组的wd： 1
元素的数据类型: int64
元素的转置 [1 2 3]


In [31]:
arr = np.array([[1,2,3],[6,7,8]])
print(arr)
print('数组的形状：',arr.shape)
print('数组的wd：',arr.ndim)
print('元素的数据类型:',arr.dtype)
print('元素的转置',arr.T)

[[1 2 3]
 [6 7 8]]
数组的形状： (2, 3)
数组的wd： 2
元素的数据类型: int64
元素的转置 [[1 6]
 [2 7]
 [3 8]]


# 三、ndarray的创建

In [33]:
#基础的创建方法
arr=np.array([1,2,3])  # []  是方法的参数。列表。list1=[4,5,6]  arr= np.array(list)
print(arr)   # 带小括号：方法

[1 2 3]


In [34]:
#copy
arr1 =np.copy(arr)
print(arr1)

[1 2 3]


In [40]:
#预定义形状

#全0 数组
arr = np.zeros((4,5),dtype=int)
print(arr)
print(arr.dtype)
print(arr.shape)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
int64
(4, 5)


In [72]:
arr = np.zeros((2,3),dtype=int)
print(arr)
print(arr.ndim)

[[[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]]
4


In [46]:
#全1 数组
arr = np.ones((5,8),dtype=int)
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [62]:
# 未初始化的 \ 未初始化    实际中较少使用
arr = np.empty((4,2))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [74]:
#固定值
arr = np.full((3,4),2026)
print(arr)
print(arr.shape)
print(arr.ndim)

[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]
(3, 4)
2


In [75]:
# like    : 形状一样 数值不一样的方法
arr2 = np.zeros_like(arr)
print(arr2)

arr2 = np.empty_like(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [79]:
#arange 等差数列  1 2 3 4 5  每次加1 ，之间的差都是 1。
arr = np.arange(1,10,1)  # start, end , step(步长)  不包含end
print(arr)

arr = np.arange(2,11,2)  # start, end , step(步长)  不包含end
print(arr)

#假设学生序号快速生成，生成指定序列使用。arr = np.arange(1,51,1)

[1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10]


In [105]:
#等间隔序列 、 等间隔数列    : 场景 学生的满分100分， 等级分数是多少
arr = np.linspace(0,4,3)  # 1，10，  1到10的长度  第三个要取几份。   写5几份中间有4个间隔
print(arr)

[0. 2. 4.]


In [101]:
arr = np.linspace(0,4,3,dtype=int)
print(arr)

arr = np.arange(0,5,2)
print(arr)

[0 2 4]
[0 2 4]


In [94]:
#对数间隔数列
arr = np.logspace(0,4,3,base=2)   #  把0 和4 分成 024三个数，再以2为底数。2的0次方 2的2次方 2的4次方
print(arr)

[ 1.  4. 16.]
